run:
 timeout: 5m
 go: "1.23"

linters-settings:
 gocyclo:
   min-complexity: 28
 lll:
   line-length: 140
 goimports:
   local-prefixes: gitlab.ozon.dev/safariproxd/homework
 gosec:
   excludes:
     - G304
     - G114
     - G112
     - G115

linters:
 disable-all: true
 enable:
   - errcheck
   - gosimple
   - govet
   - ineffassign
   - staticcheck
   - typecheck
   - unused
   - gofmt
   - gosec
   - misspell
   - gocyclo
   - unparam

issues:
 exclude-dirs:
   - vendor
   - .cache
   - bin
 exclude-files:
   - ".*_mock.go$"
   - ".*\\.pb\\.go$"
 exclude-rules:
   - path: _test\.go
     linters:
       - gosec
       - gocyclo
       - unparam
   - path: /mock/
     linters:
       - gosec
       - unused
   - text: "File is not properly formatted"
     linters:
       - goimports
   - text: "shadow: declaration of"
     linters:
       - govet