run:
  timeout: 3m
  go: "1.23"

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 140
  goimports:
    local-prefixes: gitlab.ozon.dev/safariproxd/homework

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - golint
    - gosec
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec