// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: orders/contract.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ACTION_TYPE_ISSUE       ActionType = 1
	ActionType_ACTION_TYPE_RETURN      ActionType = 2
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_ISSUE",
		2: "ACTION_TYPE_RETURN",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_ISSUE":       1,
		"ACTION_TYPE_RETURN":      2,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_contract_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_orders_contract_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{0}
}

type PackageType int32

const (
	PackageType_PACKAGE_TYPE_UNSPECIFIED PackageType = 0
	PackageType_PACKAGE_TYPE_BAG         PackageType = 1
	PackageType_PACKAGE_TYPE_BOX         PackageType = 2
	PackageType_PACKAGE_TYPE_TAPE        PackageType = 3
	PackageType_PACKAGE_TYPE_BAG_TAPE    PackageType = 4
	PackageType_PACKAGE_TYPE_BOX_TAPE    PackageType = 5
)

// Enum value maps for PackageType.
var (
	PackageType_name = map[int32]string{
		0: "PACKAGE_TYPE_UNSPECIFIED",
		1: "PACKAGE_TYPE_BAG",
		2: "PACKAGE_TYPE_BOX",
		3: "PACKAGE_TYPE_TAPE",
		4: "PACKAGE_TYPE_BAG_TAPE",
		5: "PACKAGE_TYPE_BOX_TAPE",
	}
	PackageType_value = map[string]int32{
		"PACKAGE_TYPE_UNSPECIFIED": 0,
		"PACKAGE_TYPE_BAG":         1,
		"PACKAGE_TYPE_BOX":         2,
		"PACKAGE_TYPE_TAPE":        3,
		"PACKAGE_TYPE_BAG_TAPE":    4,
		"PACKAGE_TYPE_BOX_TAPE":    5,
	}
)

func (x PackageType) Enum() *PackageType {
	p := new(PackageType)
	*p = x
	return p
}

func (x PackageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageType) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_contract_proto_enumTypes[1].Descriptor()
}

func (PackageType) Type() protoreflect.EnumType {
	return &file_orders_contract_proto_enumTypes[1]
}

func (x PackageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageType.Descriptor instead.
func (PackageType) EnumDescriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_EXPECTS     OrderStatus = 1
	OrderStatus_ORDER_STATUS_ACCEPTED    OrderStatus = 2
	OrderStatus_ORDER_STATUS_RETURNED    OrderStatus = 3
	OrderStatus_ORDER_STATUS_DELETED     OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_EXPECTS",
		2: "ORDER_STATUS_ACCEPTED",
		3: "ORDER_STATUS_RETURNED",
		4: "ORDER_STATUS_DELETED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_EXPECTS":     1,
		"ORDER_STATUS_ACCEPTED":    2,
		"ORDER_STATUS_RETURNED":    3,
		"ORDER_STATUS_DELETED":     4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_contract_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_orders_contract_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{2}
}

type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Package       *PackageType           `protobuf:"varint,4,opt,name=package,proto3,enum=orders.PackageType,oneof" json:"package,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_orders_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AcceptOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AcceptOrderRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AcceptOrderRequest) GetPackage() PackageType {
	if x != nil && x.Package != nil {
		return *x.Package
	}
	return PackageType_PACKAGE_TYPE_UNSPECIFIED
}

func (x *AcceptOrderRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AcceptOrderRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type OrderIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderIdRequest) Reset() {
	*x = OrderIdRequest{}
	mi := &file_orders_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderIdRequest) ProtoMessage() {}

func (x *OrderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderIdRequest.ProtoReflect.Descriptor instead.
func (*OrderIdRequest) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{1}
}

func (x *OrderIdRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ProcessOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        ActionType             `protobuf:"varint,2,opt,name=action,proto3,enum=orders.ActionType" json:"action,omitempty"`
	OrderIds      []uint64               `protobuf:"varint,3,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOrdersRequest) Reset() {
	*x = ProcessOrdersRequest{}
	mi := &file_orders_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOrdersRequest) ProtoMessage() {}

func (x *ProcessOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOrdersRequest.ProtoReflect.Descriptor instead.
func (*ProcessOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessOrdersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProcessOrdersRequest) GetAction() ActionType {
	if x != nil {
		return x.Action
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ProcessOrdersRequest) GetOrderIds() []uint64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InPvz         bool                   `protobuf:"varint,2,opt,name=in_pvz,json=inPvz,proto3" json:"in_pvz,omitempty"`
	LastN         *uint32                `protobuf:"varint,3,opt,name=last_n,json=lastN,proto3,oneof" json:"last_n,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_orders_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrdersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetInPvz() bool {
	if x != nil {
		return x.InPvz
	}
	return false
}

func (x *ListOrdersRequest) GetLastN() uint32 {
	if x != nil && x.LastN != nil {
		return *x.LastN
	}
	return 0
}

func (x *ListOrdersRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	CountOnPage   uint32                 `protobuf:"varint,2,opt,name=count_on_page,json=countOnPage,proto3" json:"count_on_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_orders_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetCountOnPage() uint32 {
	if x != nil {
		return x.CountOnPage
	}
	return 0
}

type ListReturnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReturnsRequest) Reset() {
	*x = ListReturnsRequest{}
	mi := &file_orders_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReturnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReturnsRequest) ProtoMessage() {}

func (x *ListReturnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReturnsRequest.ProtoReflect.Descriptor instead.
func (*ListReturnsRequest) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{5}
}

func (x *ListReturnsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ImportOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*AcceptOrderRequest  `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportOrdersRequest) Reset() {
	*x = ImportOrdersRequest{}
	mi := &file_orders_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportOrdersRequest) ProtoMessage() {}

func (x *ImportOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportOrdersRequest.ProtoReflect.Descriptor instead.
func (*ImportOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{6}
}

func (x *ImportOrdersRequest) GetOrders() []*AcceptOrderRequest {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_orders_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{7}
}

func (x *GetHistoryRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type OrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistoryRequest) Reset() {
	*x = OrderHistoryRequest{}
	mi := &file_orders_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryRequest) ProtoMessage() {}

func (x *OrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*OrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{8}
}

func (x *OrderHistoryRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*OrderHistory        `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistoryResponse) Reset() {
	*x = OrderHistoryResponse{}
	mi := &file_orders_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryResponse) ProtoMessage() {}

func (x *OrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*OrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{9}
}

func (x *OrderHistoryResponse) GetHistory() []*OrderHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_orders_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{10}
}

func (x *OrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ProcessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processed     []uint64               `protobuf:"varint,1,rep,packed,name=processed,proto3" json:"processed,omitempty"`
	Errors        []uint64               `protobuf:"varint,2,rep,packed,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResult) Reset() {
	*x = ProcessResult{}
	mi := &file_orders_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResult) ProtoMessage() {}

func (x *ProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResult.ProtoReflect.Descriptor instead.
func (*ProcessResult) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessResult) GetProcessed() []uint64 {
	if x != nil {
		return x.Processed
	}
	return nil
}

func (x *ProcessResult) GetErrors() []uint64 {
	if x != nil {
		return x.Errors
	}
	return nil
}

type OrdersList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersList) Reset() {
	*x = OrdersList{}
	mi := &file_orders_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersList) ProtoMessage() {}

func (x *OrdersList) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersList.ProtoReflect.Descriptor instead.
func (*OrdersList) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{12}
}

func (x *OrdersList) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrdersList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReturnsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Returns       []*Order               `protobuf:"bytes,1,rep,name=returns,proto3" json:"returns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnsList) Reset() {
	*x = ReturnsList{}
	mi := &file_orders_contract_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnsList) ProtoMessage() {}

func (x *ReturnsList) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnsList.ProtoReflect.Descriptor instead.
func (*ReturnsList) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{13}
}

func (x *ReturnsList) GetReturns() []*Order {
	if x != nil {
		return x.Returns
	}
	return nil
}

type OrderHistoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*OrderHistory        `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistoryList) Reset() {
	*x = OrderHistoryList{}
	mi := &file_orders_contract_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryList) ProtoMessage() {}

func (x *OrderHistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryList.ProtoReflect.Descriptor instead.
func (*OrderHistoryList) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{14}
}

func (x *OrderHistoryList) GetHistory() []*OrderHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type ImportResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imported      int32                  `protobuf:"varint,1,opt,name=imported,proto3" json:"imported,omitempty"`
	Errors        []uint64               `protobuf:"varint,2,rep,packed,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResult) Reset() {
	*x = ImportResult{}
	mi := &file_orders_contract_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResult) ProtoMessage() {}

func (x *ImportResult) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResult.ProtoReflect.Descriptor instead.
func (*ImportResult) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{15}
}

func (x *ImportResult) GetImported() int32 {
	if x != nil {
		return x.Imported
	}
	return 0
}

func (x *ImportResult) GetErrors() []uint64 {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Package       *PackageType           `protobuf:"varint,7,opt,name=package,proto3,enum=orders.PackageType,oneof" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orders_contract_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{16}
}

func (x *Order) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Order) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Order) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetPackage() PackageType {
	if x != nil && x.Package != nil {
		return *x.Package
	}
	return PackageType_PACKAGE_TYPE_UNSPECIFIED
}

type OrderHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistory) Reset() {
	*x = OrderHistory{}
	mi := &file_orders_contract_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistory) ProtoMessage() {}

func (x *OrderHistory) ProtoReflect() protoreflect.Message {
	mi := &file_orders_contract_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistory.ProtoReflect.Descriptor instead.
func (*OrderHistory) Descriptor() ([]byte, []int) {
	return file_orders_contract_proto_rawDescGZIP(), []int{17}
}

func (x *OrderHistory) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderHistory) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_orders_contract_proto protoreflect.FileDescriptor

const file_orders_contract_proto_rawDesc = "" +
	"\n" +
	"\x15orders/contract.proto\x12\x06orders\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa7\x02\n" +
	"\x12AcceptOrderRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\aorderId\x12 \n" +
	"\auser_id\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06userId\x12E\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\xfaB\a\xb2\x01\x04\b\x01@\x01R\texpiresAt\x122\n" +
	"\apackage\x18\x04 \x01(\x0e2\x13.orders.PackageTypeH\x00R\apackage\x88\x01\x01\x12\"\n" +
	"\x06weight\x18\x05 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05%\x00\x00\x00\x00R\x06weight\x12 \n" +
	"\x05price\x18\x06 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05%\x00\x00\x00\x00R\x05priceB\n" +
	"\n" +
	"\b_package\"4\n" +
	"\x0eOrderIdRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\aorderId\"\x9d\x01\n" +
	"\x14ProcessOrdersRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06userId\x126\n" +
	"\x06action\x18\x02 \x01(\x0e2\x12.orders.ActionTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06action\x12+\n" +
	"\torder_ids\x18\x03 \x03(\x04B\x0e\xfaB\v\x92\x01\b\b\x01\"\x042\x02 \x00R\borderIds\"\xc4\x01\n" +
	"\x11ListOrdersRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06userId\x12\x15\n" +
	"\x06in_pvz\x18\x02 \x01(\bR\x05inPvz\x12#\n" +
	"\x06last_n\x18\x03 \x01(\rB\a\xfaB\x04*\x02 \x00H\x00R\x05lastN\x88\x01\x01\x127\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.orders.PaginationH\x01R\n" +
	"pagination\x88\x01\x01B\t\n" +
	"\a_last_nB\r\n" +
	"\v_pagination\"V\n" +
	"\n" +
	"Pagination\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\rB\a\xfaB\x04*\x02(\x00R\x04page\x12+\n" +
	"\rcount_on_page\x18\x02 \x01(\rB\a\xfaB\x04*\x02 \x00R\vcountOnPage\"H\n" +
	"\x12ListReturnsRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.orders.PaginationR\n" +
	"pagination\"S\n" +
	"\x13ImportOrdersRequest\x12<\n" +
	"\x06orders\x18\x01 \x03(\v2\x1a.orders.AcceptOrderRequestB\b\xfaB\x05\x92\x01\x02\b\x01R\x06orders\"G\n" +
	"\x11GetHistoryRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.orders.PaginationR\n" +
	"pagination\"9\n" +
	"\x13OrderHistoryRequest\x12\"\n" +
	"\border_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\aorderId\"F\n" +
	"\x14OrderHistoryResponse\x12.\n" +
	"\ahistory\x18\x01 \x03(\v2\x14.orders.OrderHistoryR\ahistory\"W\n" +
	"\rOrderResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"E\n" +
	"\rProcessResult\x12\x1c\n" +
	"\tprocessed\x18\x01 \x03(\x04R\tprocessed\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\x04R\x06errors\"I\n" +
	"\n" +
	"OrdersList\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.orders.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"6\n" +
	"\vReturnsList\x12'\n" +
	"\areturns\x18\x01 \x03(\v2\r.orders.OrderR\areturns\"B\n" +
	"\x10OrderHistoryList\x12.\n" +
	"\ahistory\x18\x01 \x03(\v2\x14.orders.OrderHistoryR\ahistory\"B\n" +
	"\fImportResult\x12\x1a\n" +
	"\bimported\x18\x01 \x01(\x05R\bimported\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\x04R\x06errors\"\x9c\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x02R\x06weight\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x02R\n" +
	"totalPrice\x122\n" +
	"\apackage\x18\a \x01(\x0e2\x13.orders.PackageTypeH\x00R\apackage\x88\x01\x01B\n" +
	"\n" +
	"\b_package\"\x91\x01\n" +
	"\fOrderHistory\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*X\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_TYPE_ISSUE\x10\x01\x12\x16\n" +
	"\x12ACTION_TYPE_RETURN\x10\x02*\xa4\x01\n" +
	"\vPackageType\x12\x1c\n" +
	"\x18PACKAGE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PACKAGE_TYPE_BAG\x10\x01\x12\x14\n" +
	"\x10PACKAGE_TYPE_BOX\x10\x02\x12\x15\n" +
	"\x11PACKAGE_TYPE_TAPE\x10\x03\x12\x19\n" +
	"\x15PACKAGE_TYPE_BAG_TAPE\x10\x04\x12\x19\n" +
	"\x15PACKAGE_TYPE_BOX_TAPE\x10\x05*\x95\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_EXPECTS\x10\x01\x12\x19\n" +
	"\x15ORDER_STATUS_ACCEPTED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_RETURNED\x10\x03\x12\x18\n" +
	"\x14ORDER_STATUS_DELETED\x10\x042\xa0\x1b\n" +
	"\rOrdersService\x12\x90\x03\n" +
	"\vAcceptOrder\x12\x1a.orders.AcceptOrderRequest\x1a\x15.orders.OrderResponse\"\xcd\x02\x92A\xad\x02\x12-Принять заказ от курьера\x1a\xfb\x01Принимает заказ с указанным ID, ID получателя и сроком хранения. Заказ нельзя принять дважды. Если срок хранения в прошлом, выдается ошибка.\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/orders/accept\x12\xc2\x03\n" +
	"\vReturnOrder\x12\x16.orders.OrderIdRequest\x1a\x15.orders.OrderResponse\"\x83\x03\x92A\xe3\x02\x12(Вернуть заказ курьеру\x1a\xb6\x02Возвращает заказ курьеру по указанному ID. Можно вернуть только заказы, которые не находятся у клиентов или у которых истек срок хранения. Заказ помечается как удаленный.\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/orders/return\x12\xb0\x05\n" +
	"\rProcessOrders\x12\x1c.orders.ProcessOrdersRequest\x1a\x15.orders.ProcessResult\"\xe9\x04\x92A\xc8\x04\x12OВыдать заказы или принять возвраты клиента\x1a\xf4\x03Обрабатывает выдачу заказов или прием возвратов для указанного пользователя и списка заказов. Выдача возможна только для принятых заказов с неистекшим сроком хранения. Возврат возможен в течение двух суток с момента выдачи. Все заказы должны принадлежать одному клиенту.\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/orders/process\x12\xb5\x03\n" +
	"\n" +
	"ListOrders\x12\x19.orders.ListOrdersRequest\x1a\x12.orders.OrdersList\"\xf7\x02\x92A\xd2\x02\x12,Получить список заказов\x1a\xa1\x02Возвращает список заказов для указанного пользователя. Поддерживает получение последних N заказов или заказов, находящихся в ПВЗ, с опциональной пагинацией.\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/orders/list/{user_id}\x12\xf5\x02\n" +
	"\vListReturns\x12\x1a.orders.ListReturnsRequest\x1a\x13.orders.ReturnsList\"\xb4\x02\x92A\x96\x02\x12AПолучить список возвратов клиентов\x1a\xd0\x01Возвращает список возвращенных заказов с постраничной пагинацией, отсортированный от свежих возвратов к старым.\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/orders/returns\x12\xd1\x02\n" +
	"\n" +
	"GetHistory\x12\x19.orders.GetHistoryRequest\x1a\x18.orders.OrderHistoryList\"\x8d\x02\x92A\xef\x01\x12.Получить историю заказов\x1a\xbc\x01Возвращает историю изменений статуса всех заказов, отсортированную по времени последнего обновления.\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/orders/history\x12\xa8\x02\n" +
	"\fImportOrders\x12\x1b.orders.ImportOrdersRequest\x1a\x14.orders.ImportResult\"\xe4\x01\x92A\xc4\x01\x12'Импортировать заказы\x1a\x98\x01Импортирует несколько заказов из предоставленного списка, валидируя каждый заказ.\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/orders/import\x12\xd4\x03\n" +
	"\x0fGetOrderHistory\x12\x1b.orders.OrderHistoryRequest\x1a\x1c.orders.OrderHistoryResponse\"\x85\x03\x92A\xdc\x02\x12BПолучить историю статусов по заказу\x1a\x95\x02Возвращает историю изменений статуса для указанного заказа, отсортированную по убыванию времени изменения. Если заказ не найден, возвращается ошибка.\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/orders/{order_id}/historyB\xf5\x01\x92A\xc3\x01\x12\x89\x01\n" +
	"\x12PVZ Orders Service\x12lAPI для управления заказами в системе пункта выдачи заказов.2\x051.0.0\x1a\x0elocalhost:8081*\x01\x012\x10application/json:\x10application/jsonZ,gitlab.ozon.dev/safariproxd/homework/pkg/apib\x06proto3"

var (
	file_orders_contract_proto_rawDescOnce sync.Once
	file_orders_contract_proto_rawDescData []byte
)

func file_orders_contract_proto_rawDescGZIP() []byte {
	file_orders_contract_proto_rawDescOnce.Do(func() {
		file_orders_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_contract_proto_rawDesc), len(file_orders_contract_proto_rawDesc)))
	})
	return file_orders_contract_proto_rawDescData
}

var file_orders_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orders_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_orders_contract_proto_goTypes = []any{
	(ActionType)(0),               // 0: orders.ActionType
	(PackageType)(0),              // 1: orders.PackageType
	(OrderStatus)(0),              // 2: orders.OrderStatus
	(*AcceptOrderRequest)(nil),    // 3: orders.AcceptOrderRequest
	(*OrderIdRequest)(nil),        // 4: orders.OrderIdRequest
	(*ProcessOrdersRequest)(nil),  // 5: orders.ProcessOrdersRequest
	(*ListOrdersRequest)(nil),     // 6: orders.ListOrdersRequest
	(*Pagination)(nil),            // 7: orders.Pagination
	(*ListReturnsRequest)(nil),    // 8: orders.ListReturnsRequest
	(*ImportOrdersRequest)(nil),   // 9: orders.ImportOrdersRequest
	(*GetHistoryRequest)(nil),     // 10: orders.GetHistoryRequest
	(*OrderHistoryRequest)(nil),   // 11: orders.OrderHistoryRequest
	(*OrderHistoryResponse)(nil),  // 12: orders.OrderHistoryResponse
	(*OrderResponse)(nil),         // 13: orders.OrderResponse
	(*ProcessResult)(nil),         // 14: orders.ProcessResult
	(*OrdersList)(nil),            // 15: orders.OrdersList
	(*ReturnsList)(nil),           // 16: orders.ReturnsList
	(*OrderHistoryList)(nil),      // 17: orders.OrderHistoryList
	(*ImportResult)(nil),          // 18: orders.ImportResult
	(*Order)(nil),                 // 19: orders.Order
	(*OrderHistory)(nil),          // 20: orders.OrderHistory
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_orders_contract_proto_depIdxs = []int32{
	21, // 0: orders.AcceptOrderRequest.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 1: orders.AcceptOrderRequest.package:type_name -> orders.PackageType
	0,  // 2: orders.ProcessOrdersRequest.action:type_name -> orders.ActionType
	7,  // 3: orders.ListOrdersRequest.pagination:type_name -> orders.Pagination
	7,  // 4: orders.ListReturnsRequest.pagination:type_name -> orders.Pagination
	3,  // 5: orders.ImportOrdersRequest.orders:type_name -> orders.AcceptOrderRequest
	7,  // 6: orders.GetHistoryRequest.pagination:type_name -> orders.Pagination
	20, // 7: orders.OrderHistoryResponse.history:type_name -> orders.OrderHistory
	2,  // 8: orders.OrderResponse.status:type_name -> orders.OrderStatus
	19, // 9: orders.OrdersList.orders:type_name -> orders.Order
	19, // 10: orders.ReturnsList.returns:type_name -> orders.Order
	20, // 11: orders.OrderHistoryList.history:type_name -> orders.OrderHistory
	2,  // 12: orders.Order.status:type_name -> orders.OrderStatus
	21, // 13: orders.Order.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 14: orders.Order.package:type_name -> orders.PackageType
	2,  // 15: orders.OrderHistory.status:type_name -> orders.OrderStatus
	21, // 16: orders.OrderHistory.created_at:type_name -> google.protobuf.Timestamp
	3,  // 17: orders.OrdersService.AcceptOrder:input_type -> orders.AcceptOrderRequest
	4,  // 18: orders.OrdersService.ReturnOrder:input_type -> orders.OrderIdRequest
	5,  // 19: orders.OrdersService.ProcessOrders:input_type -> orders.ProcessOrdersRequest
	6,  // 20: orders.OrdersService.ListOrders:input_type -> orders.ListOrdersRequest
	8,  // 21: orders.OrdersService.ListReturns:input_type -> orders.ListReturnsRequest
	10, // 22: orders.OrdersService.GetHistory:input_type -> orders.GetHistoryRequest
	9,  // 23: orders.OrdersService.ImportOrders:input_type -> orders.ImportOrdersRequest
	11, // 24: orders.OrdersService.GetOrderHistory:input_type -> orders.OrderHistoryRequest
	13, // 25: orders.OrdersService.AcceptOrder:output_type -> orders.OrderResponse
	13, // 26: orders.OrdersService.ReturnOrder:output_type -> orders.OrderResponse
	14, // 27: orders.OrdersService.ProcessOrders:output_type -> orders.ProcessResult
	15, // 28: orders.OrdersService.ListOrders:output_type -> orders.OrdersList
	16, // 29: orders.OrdersService.ListReturns:output_type -> orders.ReturnsList
	17, // 30: orders.OrdersService.GetHistory:output_type -> orders.OrderHistoryList
	18, // 31: orders.OrdersService.ImportOrders:output_type -> orders.ImportResult
	12, // 32: orders.OrdersService.GetOrderHistory:output_type -> orders.OrderHistoryResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_orders_contract_proto_init() }
func file_orders_contract_proto_init() {
	if File_orders_contract_proto != nil {
		return
	}
	file_orders_contract_proto_msgTypes[0].OneofWrappers = []any{}
	file_orders_contract_proto_msgTypes[3].OneofWrappers = []any{}
	file_orders_contract_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_contract_proto_rawDesc), len(file_orders_contract_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_contract_proto_goTypes,
		DependencyIndexes: file_orders_contract_proto_depIdxs,
		EnumInfos:         file_orders_contract_proto_enumTypes,
		MessageInfos:      file_orders_contract_proto_msgTypes,
	}.Build()
	File_orders_contract_proto = out.File
	file_orders_contract_proto_goTypes = nil
	file_orders_contract_proto_depIdxs = nil
}
