global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'pvz-cluster'
    replica: 'prometheus-1'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'pvz-service'
    static_configs:
      - targets: ['app:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: false
    honor_timestamps: true
    scheme: http
